plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.iabur'
version = '0.0.1-SNAPSHOT'
description = 'core'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {

}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java

            groupId = 'com.iabur'
            artifactId = 'core'
            version = '0.0.1-SNAPSHOT'
        }
    }
}
